# Generated by Django 3.1.1 on 2020-10-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.horario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariocustomizado')),
            ],
        ),
    ]
