# Generated by Django 3.1.1 on 2020-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Especialidade'),
        ),
    ]
