# Generated by Django 3.1.1 on 2020-10-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201005_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
