# Generated by Django 3.1.1 on 2020-10-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horarios', models.ManyToManyField(to='agenda.Horario')),
                ('medico', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
        ),
    ]
